name: pointnet
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8  # or your preferred version
  - pytorch     # you can specify version, e.g., pytorch=1.12.0
  - tqdm
  - pip
  - pip:
      - plyfile
      - -e .  # install your local package in editable mode
